@extends('layouts.app')

@section('page_title', 'Bajas')

@section('breadcrumbs')<li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Inicio</a></li><li class="breadcrumb-item active">Bajas</li>@endsection

@section('content')
@include('human_resources.partials.flash')
<div class="card"><div class="card-header"><h4 class="card-title mb-0">Historial de bajas</h4></div><div class="card-body border-bottom"><form method="GET" class="row g-2"><div class="col-md-5"><select class="form-select form-select-sm" name="termination_type"><option value="">Todos los tipos</option><option value="resignation" @selected($terminationType === 'resignation')>Renuncia</option><option value="dismissal" @selected($terminationType === 'dismissal')>Despido</option><option value="rest" @selected($terminationType === 'rest')>Descanso</option></select></div><div class="col-md-6"><select class="form-select form-select-sm" name="project_work_id"><option value="">Todas las obras</option>@foreach($projectWorks as $projectWork)<option value="{{ $projectWork->id }}" @selected((string) $projectWorkId === (string) $projectWork->id)>{{ $projectWork->name }}</option>@endforeach</select></div><div class="col-md-1 d-grid"><button class="btn btn-sm btn-outline-primary"><i class="ri-search-line"></i></button></div></form></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="bg-light-subtle"><tr><th>Fecha</th><th>Trabajador</th><th>Tipo</th><th>Obra</th><th>Motivo</th><th class="text-end">Ver</th></tr></thead><tbody>@forelse($terminations as $termination)<tr><td>{{ $termination->termination_date->format('d/m/Y') }}</td><td>{{ $termination->worker->first_name }} {{ $termination->worker->last_name }}</td><td>{{ ['resignation' => 'Renuncia', 'dismissal' => 'Despido', 'rest' => 'Descanso'][$termination->termination_type] }}</td><td>{{ $termination->projectWork?->name ?: '—' }}</td><td>{{ $termination->reason ?: '—' }}</td><td class="text-end"><a class="btn btn-light btn-sm" href="{{ route('human_resources.worker-terminations.show', $termination) }}"><i class="ri-eye-line"></i></a></td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-4">No hay bajas registradas.</td></tr>@endforelse</tbody></table></div>@if($terminations->hasPages())<div class="card-footer d-flex justify-content-end">{{ $terminations->links('pagination::bootstrap-5') }}</div>@endif</div>
@endsection