@extends('layouts.app')
@section('page_title', 'Inventario')
@section('breadcrumbs')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Inicio</a></li>
    <li class="breadcrumb-item active">Inventario</li>
@endsection
@section('content')
@if($overdueLoans->isNotEmpty())
<div class="alert alert-warning alert-dismissible fade show" role="alert"><i class="ri-alarm-warning-line me-1"></i><strong>Herramientas con retorno vencido:</strong> {{ $overdueLoans->count() }}<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>
@endif
<div class="card">
    <div class="card-header d-flex flex-wrap justify-content-between align-items-center gap-2 border-bottom">
        <div><h4 class="card-title mb-0"><i class="ri-archive-line text-primary me-1"></i>Consulta de inventario</h4><span class="text-muted fs-13">Existencias actuales por suministro</span></div>
        <div class="d-flex gap-2"><a href="{{ route('stocks.entries.index') }}" class="btn btn-sm btn-outline-primary"><i class="ri-inbox-line me-1"></i>Entradas</a><a href="{{ route('stocks.exits.index') }}" class="btn btn-sm btn-outline-primary"><i class="ri-arrow-right-circle-line me-1"></i>Salidas</a></div>
    </div>
    <div class="card-body border-bottom py-3"><form method="GET" action="{{ route('stocks.index') }}" class="d-flex gap-2"><div class="input-group input-group-sm" style="max-width:540px"><span class="input-group-text bg-light"><i class="ri-search-line text-muted"></i></span><input name="search" value="{{ $search }}" class="form-control" placeholder="Código, descripción o ubicación" autocomplete="off">@if($search)<a href="{{ route('stocks.index') }}" class="btn btn-outline-secondary" title="Limpiar búsqueda"><i class="ri-close-line"></i></a>@endif<button class="btn btn-primary">Buscar</button></div></form></div>
    <div class="card-body p-0"><div class="table-responsive"><table class="table align-middle table-hover table-centered mb-0"><thead class="bg-light-subtle"><tr><th>Código</th><th>Descripción</th><th>Ubicación</th><th class="text-end">Stock actual</th><th class="text-end">Mínimo</th><th class="text-end">Máximo</th><th>Último movimiento</th><th></th></tr></thead><tbody>@forelse($concepts as $concept)@php($isEntry = $concept->last_movement_type === 'entry')<tr><td><a href="{{ route('stocks.show', $concept) }}" class="fw-semibold text-primary text-decoration-none">{{ $concept->code }}</a><span class="d-block text-muted fs-12">{{ $concept->unit }}</span></td><td><span class="hover-marquee d-block" style="--marquee-width:340px;" title="{{ $concept->description }}"><span class="track"><span>{{ $concept->description }}</span><span aria-hidden="true">{{ $concept->description }}</span></span></span></td><td><i class="ri-map-pin-line text-muted me-1"></i>{{ $concept->warehouse_location }}</td><td class="text-end"><span class="fw-bold fs-15">{{ rtrim(rtrim(number_format((float) $concept->current_stock, 3, '.', ''), '0'), '.') }}</span>@if($concept->last_movement_type)<i class="{{ $isEntry ? 'ri-arrow-up-line text-success' : 'ri-arrow-down-line text-danger' }} fs-18 ms-1" title="{{ $isEntry ? 'Último movimiento: entrada' : 'Último movimiento: salida' }}"></i>@endif</td><td class="text-end text-muted">{{ $concept->minimum_stock ?? '—' }}</td><td class="text-end text-muted">{{ $concept->maximum_stock ?? '—' }}</td><td>@if($concept->last_movement_type)<span class="badge {{ $isEntry ? 'bg-success-subtle text-success' : 'bg-danger-subtle text-danger' }} py-1 px-2 fs-12"><i class="{{ $isEntry ? 'ri-arrow-up-line' : 'ri-arrow-down-line' }} me-1"></i>{{ $isEntry ? 'Entrada' : 'Salida' }}</span><small class="d-block text-muted fs-11 mt-1">{{ $concept->last_movement_at?->format('d/m/Y') }}</small>@else<span class="text-muted fs-12">Sin movimientos</span>@endif</td><td class="text-end"><a href="{{ route('stocks.show', $concept) }}" class="btn btn-light btn-sm" title="Ver histórico"><i class="ri-history-line"></i></a></td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-4"><i class="ri-archive-line fs-24 d-block mb-1 opacity-50"></i>No hay suministros con los filtros seleccionados.</td></tr>@endforelse</tbody></table></div></div>
    @if($concepts->hasPages())<div class="card-footer d-flex justify-content-end">{{ $concepts->links('pagination::bootstrap-5') }}</div>@endif
</div>
@endsection
