@extends('layouts.app')
@section('page_title', 'Inventario')
@section('breadcrumbs')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Inicio</a></li>
    <li class="breadcrumb-item active">Inventario</li>
@endsection
@section('content')
@if($overdueLoans->isNotEmpty())
<div class="alert alert-warning"><strong>Herramientas con retorno vencido:</strong> {{ $overdueLoans->count() }}</div>
@endif
<div class="card mb-3"><div class="card-header d-flex justify-content-between align-items-center border-bottom"><h4 class="card-title mb-0">Existencias</h4><form method="GET" class="d-flex gap-2"><input name="search" value="{{ $search }}" class="form-control form-control-sm" placeholder="Código, descripción o ubicación"><button class="btn btn-primary btn-sm"><i class="ri-search-line"></i></button></form></div><div class="card-body p-0"><div class="table-responsive"><table class="table align-middle text-nowrap table-hover table-centered mb-0"><thead class="bg-light-subtle"><tr><th>Código</th><th>Descripción</th><th>Unidad</th><th>Ubicación</th><th class="text-end">Stock actual</th><th class="text-end">Mínimo</th><th class="text-end">Máximo</th></tr></thead><tbody>@forelse($concepts as $concept)<tr><td class="fw-semibold">{{ $concept->code }}</td><td class="text-wrap">{{ $concept->description }}</td><td>{{ $concept->unit }}</td><td>{{ $concept->warehouse_location }}</td><td class="text-end">{{ number_format($concept->current_stock, 3) }}</td><td class="text-end">{{ $concept->minimum_stock ?? '—' }}</td><td class="text-end">{{ $concept->maximum_stock ?? '—' }}</td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">No hay conceptos registrados.</td></tr>@endforelse</tbody></table></div></div>@if($concepts->hasPages())<div class="card-footer d-flex justify-content-end">{{ $concepts->links('pagination::bootstrap-5') }}</div>@endif</div>
<ul class="nav nav-tabs nav-tabs-custom mb-0" role="tablist"><li class="nav-item"><button class="nav-link active" data-bs-toggle="tab" data-bs-target="#entries">Entradas</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#exits">Salidas</button></li></ul><div class="tab-content border border-top-0 p-3"><div class="tab-pane fade show active" id="entries"><table class="table align-middle text-nowrap mb-0"><thead><tr><th>Fecha</th><th>Código</th><th>Tipo</th><th class="text-end">Cantidad</th></tr></thead><tbody>@foreach($entries as $entry)<tr><td>{{ $entry->received_at->format('d/m/Y') }}</td><td>{{ $entry->concept?->code ?? $entry->tool?->economic_number }}</td><td>{{ $entry->entry_type === 'purchase' ? 'Compra' : 'Retorno' }}</td><td class="text-end">{{ $entry->quantity }}</td></tr>@endforeach</tbody></table></div><div class="tab-pane fade" id="exits"><table class="table align-middle text-nowrap mb-0"><thead><tr><th>Fecha</th><th>Código</th><th>Tipo</th><th class="text-end">Cantidad</th></tr></thead><tbody>@foreach($exits as $exit)<tr><td>{{ $exit->exited_at->format('d/m/Y') }}</td><td>{{ $exit->concept?->code ?? $exit->tool?->economic_number }}</td><td>{{ $exit->exit_type === 'definitive' ? 'Definitiva' : 'Préstamo' }}</td><td class="text-end">{{ $exit->quantity }}</td></tr>@endforeach</tbody></table></div></div>
@endsection
